#pragma config(Sensor, S2,     IRfront,        sensorI2CCustom)
#pragma config(Sensor, S1,     IRback,         sensorI2CCustom)
#pragma config(Sensor, S3,     Compass,        sensorEV3_GenericI2C)
#pragma config(Motor,  motorA,          brPF,          tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          blPF,          tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,          tlPF,          tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorD,          trPF,          tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v2.h" //IRsensor Library
#include "PF_Motors.h" // PF Motor Library
#include "PF_Motors.c" // PF Motor Library

#define COMP_MULTI 0.7 //Compass Multiplier (Sense of Direction in degrees)

int programstart;
int currentcompass;

task main()
{
	tHTIRS2 irSeeker1;
	tHTIRS2 irSeeker2;
	initSensor(&irSeeker1, IRfront);
	initSensor(&irSeeker2, IRback);
	initPFMotors();
	startMotorTask();
	programstart = SensorValue[S3];
	while(true){
		currentcompass = SensorValue[S3];
		if(programstart == currentcompass) {
			motorsIn.structure.A = 0;
			motorsIn.structure.B = 0;
			motorsIn.structure.C = 0;
			motorsIn.structure.D = 0;
		else if(programstart < currentcompass) { //tl, br
			motorsIn.structure.A = 70;
			motorsIn.structure.B = 0;
			motorsIn.structure.C = 70;
			motorsIn.structure.D = 0;
		else {
			motorsIn.structure.A = 0;
			motorsIn.structure.B = 70;
			motorsIn.structure.C = 0;
			motorsIn.structure.D = 70;
		}
	}
}
