#pragma config(Motor,  motorA,          tlPF,          tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorB,          trPF,          tmotorEV3_Large, openLoop, encoder)
#pragma config(Motor,  motorC,          brPF,          tmotorEV3_Large, openLoop, reversed, encoder)
#pragma config(Motor,  motorD,          blPF,          tmotorEV3_Large, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "PF_Motors.h" // PF Motor Library
#include "PF_Motors.c" // PF Motor Library
//int motorSpeeds[18][4] = { //Defining movement
//    { -100, -100,  100,  100}, // Forward
 //   { -100,   20, -100,   20}, // Forward-Right
  //  { -100,  100,  100, -100}, // Right
   // {    0,  100,    0, -100}, // Backward
    //{  100,  100, -100, -100}, // Backward
  //  {  100,    0, -100,    0}, // Backward
  //  {  100, -100, -100,  100}, // Left
  //  {   20, -100,   20,  100}, // Forward-Left
  //  {    0,    0,    0,    0}, // Still
  //  {  100,  100, -100, -100}, // Forward
   // {  100,    0, -100,    0}, // Forward-Right
    //{  100, -100, -100,  100}, // Right
    //{    0, -100,    0,  100}, // Backward-Right
    //{ -100, -100,  100,  100}, // Backward
    //{ -100,    0,  100,    0}, // Backward-Left
    //{ -100,  100,  100, -100}, // Left
    //{    0,  100,    0, -100}, // Forward-Left
    //{    0,    0,    0,    0}, // Still
//};

task main()
{
	initPFMotors();
	startMotorTask();
		motorIn.structure.A = 0;
		motorIn.structure.B = 100;
		motorIn.structure.C = 0;
		motorIn.structure.D = 100;
}
